services:
  geminabox:
    build:
      context: .
      platforms:
        - linux/amd64
    image: geminabox:latest
    platform: linux/amd64
    container_name: geminabox
    restart: unless-stopped
    expose:
      - "9292"
    volumes:
      - gem-data:/data/geminabox
    environment:
      - RACK_ENV=production
      - WEB_CONCURRENCY=2
      - MAX_THREADS=5
      - GEMINABOX_USERNAME=xxx
      - GEMINABOX_PASSWORD=xxx

  nginx:
    image: nginx:stable-alpine
    container_name: geminabox-nginx
    restart: unless-stopped
    depends_on:
      - geminabox
    ports:
      - "80:80"
      # 如果后续要配 HTTPS，再打开 443
      # - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/geminabox.conf:ro

volumes:
  gem-data:
    driver: local
