services:
  geminabox:
    build:
      context: .
      platforms:
        - linux/amd64
    image: geminabox:latest
    platform: linux/amd64
    container_name: geminabox
    restart: unless-stopped
    ports:
      - "9292:9292"
    volumes:
      - gem-data:/geminabox-data
    environment:
      - RACK_ENV=production
      - WEB_CONCURRENCY=2
      - MAX_THREADS=5
      - GEMINABOX_USERNAME=xxx
      - GEMINABOX_PASSWORD=xxx

volumes:
  gem-data:
    driver: local
